export const cartTypesActions = {
    TOOGLE_CART_HIDDEN:  'TOOGLE_CART_HIDDEN',
    ADD_ITEM: "ADD_ITEM",
    CLERA_ITEM_FROM_CART: "CLERA_ITEM_FROM_CART",
    REDUCE_ITEM: "REDUCE_ITEM",
    CLEAR_CART: "CLEAR_CART",
    SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE",
    UPDATE_CART_IN_FIREBASE: "UPDATE_CART_IN_FIREBASE"
}